n = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(n))
print('Só tem espaços?', n.isspace())
print('É um numero? ', n.isnumeric())
print('Isso é Alfabetico? ',n.isalpha())
print('Isso é Alfanumerico? ', n.isalnum())
print('Está só com letras maiusculas? ', n.isupper())
print('Está só com letras minusculas? ', n.islower())
print('Está captalizada? ', n.istitle())
